version: "3.9"

services:
  ml-service-blue:
    image: ghcr.io/artemprisiazhniuk/mlops_hw3_prisiazhniuk_artem-blue:${IMAGE_TAG}
    environment:
      APP_VERSION: "blue"
      MODEL_VERSION: "v1.0.0"
    ports:
      - "8081:8080"

networks:
  default:
    name: demo-net