services:
  nginx:
    image: nginx:latest
    ports:
      - "8086:80"
    volumes:
      - ./nginx/nginx.blue.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ml-service-blue
      - ml-service-green

networks:
  default:
    name: demo-net